[package]

name = "event"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>"
]
tags = []

[lib]

name = "event"
path = "src/lib.rs"

[dependencies.piston]

git = "https://github.com/pistondevelopers/piston/"

